name: Pull Request CI

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    with:
      skip-dependency-check: false

  pr-summary:
    needs: [tests]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: PR Status Summary
        run: |
          echo "## Pull Request CI Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "${{ needs.tests.result }}" == "success" ]; then
            echo "✅ **All tests passed!**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "- 📦 Tests completed successfully across Node.js versions  20, 22" >> $GITHUB_STEP_SUMMARY
            echo "- 🔍 Code quality checks passed" >> $GITHUB_STEP_SUMMARY
            echo "- 🔒 Security audit completed" >> $GITHUB_STEP_SUMMARY
            echo "- 🏗️ Build artifacts verified" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "🚀 **Ready for review and merge**" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Tests failed**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Please check the test results and fix any issues before requesting review." >> $GITHUB_STEP_SUMMARY
          fi
